"""Adiciona segunda pausa

Revision ID: 2870d846a733
Revises: 
Create Date: 2026-03-19 09:36:33.352852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2870d846a733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause2_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('pause2_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_schedules', schema=None) as batch_op:
        batch_op.drop_column('pause2_end')
        batch_op.drop_column('pause2_start')

    # ### end Alembic commands ###
